[project]
name = "honda-nodes"
description = "A specialized node pack heavily focused on secure image metadata editing and manipulation, supported by a suite of JSON, text, and file system automation tools. Optimized for the V3 API (Nodes 2.0)."
version = "1.0.0"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "comfyui-frontend-package>=1.50.0"
]
classifiers = [
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS"
]

[project.urls]
Repository = "https://github.com/Avaray/honda-nodes"
Homepage = "https://dav.one/image-metadata-editor/"

[tool.comfy]
PublisherId = "avaray"
DisplayName = "⚡️ Honda Nodes"
Icon = "https://raw.githubusercontent.com/Avaray/honda-nodes/main/icon.png"
requires-comfyui = ">=0.38.0"
